<?php

require_once __DIR__ . '/vendor/autoload.php';
use \tuana8tmt\TextExtract\StopWords\StopWords;
use \tuana8tmt\TextExtract\Rake;


$text = 'As we stood waiting for a taxi outside of the airport, it was immediately apparent to me that New York City was not the same as New Caney, Texas. It seemed like everyone there was in a hurry to get to another place. The loud and constant sound of cars honking was heard throughout the entire trip. As soon as a car seemed to be going slower than the person behind him liked, he would hear the horn of that car to let him know that he was apparently holding everybody else up! When we found our hotel in Times Square, I noticed that it wasn’t just the cars that were in a hurry. Everyone in the streets was walking at a brisk pace that indicated a rush to be somewhere. The transportation of the city was also far different than anything that I had ever been exposed to. In my little town, a bike, a car, or even walking was perfectly suitable for getting around town, but in this foreign land, there were many more ways for one to get to another destination. Everywhere you looked, there were people hailing taxis, waiting on buses, rushing underground to the subway stations, walking frantically, or desperately trying to maneuver their own cars through the busy streets. Just standing and watching the many people rushing their own separate ways was an interesting observation.
In addition to the people and transportation, the buildings were also an incredible sight. Each street was crammed with buildings that were built side by side with no room in between them, and a number of skyscrapers were present throughout the city as well. I was awestruck again as we went inside some of these buildings such as the Empire State Building and made our way towards the top. Standing outside of one of the top stories of the Empire State Building was awesome. I could hold the entire city in my hand from this view. I could even see Ellis Island a distance away from there. The stores were also large compared to the ones of my little town. A small retail store in New Caney would be a huge store that took up an entire building in New York. This would make it seem logical that the prices of everything in New York were almost triple those back home. It was as if the little peaceful neighborhood where I lived was magnified by 100 to make up the wonder city of New York.';
$stop_word = new Rake();
$stop_word->extract($text, 'en',10);
print_r($stop_word->scores_limit);
